### GET actuator
GET {{host}}/actuator

### GET health
GET {{host}}/actuator/health

### GET hello world
GET {{host}}/api/v1/hello

### GET hello bad
GET {{host}}/api/v1/hello?name=bad

### GET env as plain
GET {{host}}/api/v1/env

### GET env HOME as plain
GET {{host}}/api/v1/env?key=HOME

### GET env as json
GET {{host}}/api/v1/env
Accept: application/json

### GET env HOME as json
GET {{host}}/api/v1/env?key=HOME
Accept: application/json

### POST echo json
POST {{host}}/api/v1/echo
Content-Type: application/json
foo: Bar

{"id":42,"foo":"bar"}

### POST echo csv
POST {{host}}/api/v1/echo
Accept: application/json
Content-Type: application/csv
fein: fein

fein,fein,fein,fein

### GET dynamodb tables
GET {{host}}/api/v1/tables
Accept: application/json
