### GET actuator
GET {{host}}/actuator

### GET health
GET {{host}}/actuator/health

### GET hello world
GET {{host}}/ecsdemo/hello

### GET hello bad
GET {{host}}/ecsdemo/hello?name=bad

### GET env as plain
GET {{host}}/ecsdemo/env

### GET env HOME as plain
GET {{host}}/ecsdemo/env?key=HOME

### GET env as json
GET {{host}}/ecsdemo/env
Accept: application/json

### GET env HOME as json
GET {{host}}/ecsdemo/env?key=HOME
Accept: application/json

### POST echo json
POST {{host}}/ecsdemo/echo
Content-Type: application/json
foo: Bar

{"id":42,"foo":"bar"}

### POST echo csv
POST {{host}}/ecsdemo/echo
Accept: application/json
Content-Type: application/csv
fein: fein

fein,fein,fein,fein
